5 game home page
GSG-CF05/GAMSIC pull request #38
Opened 2022-03-21 17:22 UTC by yasmeentayeh99

create music home page , added img , title , describtion and button , 
put header contain arrow icon and toggle icon 
create css file contain animation , media query and style css

2022-03-21 19:34 UTC, shamskhodary requested changes

2022-03-21 19:34 UTC, shamskhodary commented on home-game/home-game.html
> +  <i class="ri-arrow-right-s-line"></i>
You should link the right arrow to the previous page "landing page".

2022-03-22 06:03 UTC, moustf requested changes

2022-03-22 06:03 UTC, moustf commented on home-game/home-game.css
> +        margin-left: 11rem;
The left margin in this media query in't necessary, delete it to put it to zero because it's too much.

2022-03-22 06:03 UTC, moustf commented on home-game/home-game.html
> +      <button class="btn"> <a href="#"> Learn More </a> </button>
You should link the button to the next page when the user wants to go for further information.

2022-03-23 20:25 UTC, closed without merging